[[redirects]]
  from = "/podcast-assets/*"
  to = "https://virtualcoffeeio-assets.storage.googleapis.com/podcast-assets/:splat"
  status = 200
  force = true

 [[redirects]]
  from = "/"
  to = "https://virtualcoffee.io"
